### ISSUE TITLE
glog-config.cmake is missing in INSTALL directory in Windows 10

### ISSUE THREAD

**Issue by jasjuang** [google/glog#150] opened 2017-01-02 20:12 UTC
I am on Visual studio 2015 and Windows 10.

I install glog through the standard procedure of

``````
git clone https://github.com/google/glog/
mkdir build 
cd build
cmake -A x64 ..
It generates a solution file. I build the entire solution and build the INSTALL project.
``````

However, when I am cmaking with [Ceres](https://github.com/ceres-solver/ceres-solver/) that uses glog, there is an error "Failed to find installed glog CMake configuration", which I believe is because it is looking for the file glog-config.cmake but it is not there. I think it should be there because when I go through the same procedure to INSTALL [gflags](https://github.com/gflags/gflags), which is also being used by Ceres,   the INSTALL folder of gflags has "include" folder, "lib" folder and "cmake" folder that has gflags-config.cmake, whereas in glog there is only the "include" folder and "lib" folder and glog-config.cmake is no where to be seen.

**Comment by sergiud** [comment] 2017-01-02 20:17
It's under `lib/cmake/glog`.

**Comment by jasjuang** [comment] 2017-01-02 20:19
oops you are right, then it's a Ceres problem

**Comment by jasjuang** [comment] 2017-01-04 01:55
After further research, it is not Ceres's fault that it can't find glog-config.cmake. It's actually a problem of glog. If you take a look [here](https://cmake.org/cmake/help/v3.0/command/find_package.html), in the middle section it shows 

``````
<prefix>/                                                                            (W)
<prefix>/(cmake|CMake)/                                                  (W)
<prefix>/<name>*/                                                             (W)
<prefix>/<name>*/(cmake|CMake)/                                   (W)
<prefix>/(lib/<arch>|lib|share)/cmake/<name>*/                 (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/                             (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/  (U)
``````

on where to find the config file. Gflags does it correctly and put it in `<prefix>/<name>*/(cmake|CMake)/    ` hence Ceres is able to find it, glog puts it in `<prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/ ` which is a unix default search path hence Ceres fails to find it on windows. 

@sergiud could you look into it? Thanks

**Comment by sergiud** [comment] 2017-01-04 07:06
You're incorrect. CMake understands Unix conventions on Windows as well. 

If you still see a problem, please provide a minimal test case.

**Comment by jasjuang** [comment] 2017-01-04 17:26
No it won't. Below is the minimal example to reproduce it. Only two files are needed.

CMakeLists.txt

``````
cmake_minimum_required(VERSION 3.5)
project(Sample)

set(PROJECT_SRCS
${PROJECT_SOURCE_DIR}/SampleExample.cpp
)

find_package( GFLAGS REQUIRED )
find_package( GLOG REQUIRED )

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})
``````
SampleExample.cpp

``````
int main(){
  return 0;
}
``````

If you open cmake-gui with windows, GLAGS_DIR is `C:/Program Files (x86)/gflags/CMake` which is as expected because they put their gflags-config.cmake in their right location, but GLOG_DIR is shown as GLOG_DIR-NOTFOUND.

Here is the command line output with `cmake -A x64 ..`

``````
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindGLOG.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GLOG", but
  CMake did not find one.

  Could not find a package configuration file provided by "GLOG" with any of
  the following names:

    GLOGConfig.cmake
    glog-config.cmake

  Add the installation prefix of "GLOG" to CMAKE_PREFIX_PATH or set
  "GLOG_DIR" to a directory containing one of the above files.  If "GLOG"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
``````

**Comment by sergiud** [comment] 2017-01-04 19:18
I've no idea what you're doing. I'm on Windows myself and glog works just fine for me.

My guess is that you're using CMake incorrectly. Have you read the error message about the `CMAKE_PREFIX_PATH`?

**Comment by sergiud** [comment] 2017-01-04 20:03
So this issue is a duplicate of #149 .

As I already mentioned there, you can set `CMAKE_INSTALL_PREFIX` until the problem is resolved.

**Closed** 2017-10-24 08:15 UTC
Labels: duplicate, invalid

**Comment by wangzhankun** [comment] 2020-11-18 16:24
I have no idea about cmake, could you please give an example for how to configure the ```glog_DIR```?  
 
I configure it by using ```cmake -Dglog_DIR=/usr/include/glog  ..```, but it is stilled failed.
