### ISSUE TITLE
glog make install doesn't correctly install glog-modules.cmake

### ISSUE THREAD

**Issue by adisuciu** [google/glog#736] opened 2021-11-09 10:22 UTC
Version - 33696664cba5737098546adcd8e4938730312a69

https://github.com/google/glog/pull/733 - this broke glog install with CMAKE_INSTALL_PREFIX

https://gist.github.com/adisuciu/9059db71c3ea947e81ea98053c3b9398 - bad install - you can see the install location of glog-modules.cmake - 
`-- Installing: /home/adi/glog/build/lib/cmake/glog/glog-modules.cmake
`
Resetting glog to 17e7679fd9beb95277ccd0708056ba85363f892b fixes it https://gist.github.com/adisuciu/b0c787025d874d8bfeb082cf20cf6526

**Comment by sergiud** [comment] 2021-11-09 11:00
@nh2 Please take a look.

**Comment by r-burns** [comment] 2021-11-11 04:00
Seems like cmake `install(CODE` loses its install prefix context, not sure why. Would something like this fix it?

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1019,6 +1019,12 @@ set (glog_FULL_CMake_DATADIR
 configure_file (glog-modules.cmake.in
   ${CMAKE_CURRENT_BINARY_DIR}/glog-modules.cmake @ONLY)
 
+if (IS_ABSOLUTE "${_glog_CMake_INSTALLDIR}")
+    set (_glog_FULL_CMake_INSTALLDIR "${_glog_CMake_INSTALLDIR}")
+else ()
+    set (_glog_FULL_CMake_INSTALLDIR "${CMAKE_INSTALL_PREFIX}/${_glog_CMake_INSTALLDIR}")
+endif ()
+
 install (CODE
 "
 set (glog_FULL_CMake_DATADIR \"\\\${CMAKE_CURRENT_LIST_DIR}/${glog_REL_CMake_DATADIR}\")
@@ -1027,7 +1033,7 @@ configure_file (\"${CMAKE_CURRENT_SOURCE_DIR}/glog-modules.cmake.in\"
 file (INSTALL
   \"${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/glog-modules.cmake\"
   DESTINATION
-  \"${_glog_CMake_INSTALLDIR}\")
+  \"${_glog_FULL_CMake_INSTALLDIR}\")
 "
   COMPONENT Development
 )
```

**Comment by sergiud** [comment] 2021-11-11 09:59
@r-burns I'm not sure I understand your use case. `_glog_CMake_INSTALLDIR` uses `CMAKE_INSTALL_LIBDIR` which is appended to `CMAKE_INSTALL_PREFIX`, i.e., it is not expected to be an absolute path.

Do you set `CMAKE_INSTALL_*` CMake variables to absolute paths?

**Comment by jtojnar** [comment] 2021-11-11 10:40
@sergiud  Yes, #733 was made to support absolute paths in `GNUInstallDirs` options, without realizing that `file (INSTALL …)` will [target the build directory](https://cmake.org/cmake/help/latest/command/file.html?highlight=%20Relative%20destination#install) when a relative destination path is passed to it (unlike most other commands which install relative to prefix).

Do you know the reason `eval` (`install (CODE …)`) is used rather than calling `install` command directly? It appears to originate from https://github.com/google/glog/commit/9a43cfb8d2fa17eea27c73cf3f812de1df3b5e93 without much of an explanation.

**Comment by sergiud** [comment] 2021-11-11 10:53
The reason for using `install (CODE ...)` is that both `CMAKE_CURRENT_LIST_DIR` and `CMAKE_INSTALL_PREFIX` must remain unevaluated during CMake configuration time with the former evaluated on use and the latter during install. Some variables are required to be eagerly evaluated though (e.g., `CMAKE_CURRENT_BINARY_DIR` and `CMAKE_FILES_DIRECTORY`). This allows `FindUnwind.cmake` to be found whenever the glog CMake package config is used both from the build directory and once installed.

If your use case involves setting `GNUInstallDirs` variables to absolute path, the initial implementation in glog was correct and the changes from #733 are invalid.

**Comment by jtojnar** [comment] 2021-11-11 11:12
> If your use case involves setting `GNUInstallDirs` variables to absolute path, the initial implementation in glog was correct and the changes from #733 are invalid.

We have absolute both `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_PREFIX` so the previous code resulted in doubling the prefix:

```cmake
set (_glog_CMake_LIBDIR ${CMAKE_INSTALL_LIBDIR})
set (_glog_CMake_INSTALLDIR ${_glog_CMake_LIBDIR}/cmake/glog)
# […]
DESTINATION
  \"\${CMAKE_INSTALL_PREFIX}/${_glog_CMake_INSTALLDIR}\")
```

> The reason for using `install (CODE ...)` is that both `CMAKE_CURRENT_LIST_DIR` and `CMAKE_INSTALL_PREFIX` must remain unevaluated during CMake configuration time with the former evaluated on use and the latter during install.

I understand that we generate a cmake module that will be loaded by other build systems so we do not want to hardcode some variables but I would expect that to be already achieved using `@ONLY`. I do not see why we must not evaluate the install variables during the configure – should not all values necessary to install be already determinable during the configure step? Or we might achieve that using [CMake generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#output-related-expressions).

**Comment by sergiud** [comment] 2021-11-11 11:40
`@ONLY` duration configuration time will not work here as `glog_FULL_CMake_DATADIR` varies between build directory and install directory and I would like to avoid duplicating the logic for both variants.

Generator expressions will unnecessarily complicate the implementation requiring to deal with multiple `.cmake` files and I'm not sure this will even work.

**Comment by sergiud** [comment] 2021-11-11 12:04
@r-burns This one works seems to work for me (I've escaped `CMAKE_INSTALL_PREFIX` to prevent its expansion):
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 990daa4..bcf04c6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1022,12 +1022,18 @@ configure_file (glog-modules.cmake.in
 install (CODE
 "
 set (glog_FULL_CMake_DATADIR \"\\\${CMAKE_CURRENT_LIST_DIR}/${glog_REL_CMake_DATADIR}\")
+set (glog_DATADIR_DESTINATION ${_glog_CMake_INSTALLDIR})
+
+if (NOT IS_ABSOLUTE ${_glog_CMake_INSTALLDIR})
+  set (glog_DATADIR_DESTINATION \"\${CMAKE_INSTALL_PREFIX}/\${glog_DATADIR_DESTINATION}\")
+endif (NOT IS_ABSOLUTE ${_glog_CMake_INSTALLDIR})
+
 configure_file (\"${CMAKE_CURRENT_SOURCE_DIR}/glog-modules.cmake.in\"
   \"${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/glog-modules.cmake\" @ONLY)
 file (INSTALL
   \"${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/glog-modules.cmake\"
   DESTINATION
-  \"${_glog_CMake_INSTALLDIR}\")
+  \"\${glog_DATADIR_DESTINATION}\")
 "
   COMPONENT Development
 )
```

**Comment by r-burns** [comment] 2021-11-11 12:13
Thanks, can confirm that's working with an absolute CMAKE_INSTALL_LIBDIR. That's also good to know w.r.t. file(INSTALL behavior, seems very unintuitive that it's based on the build directory.

**Comment by nh2** [comment] 2021-11-11 13:17
Great, thanks for looking into it!

I started investigating it 2 days ago and composed the following message, but that's probably pointless now as you've already found a solution. Compying my original message below in case it becomes relevant (unlikely since the people from whom I quote those ideas are already on this thread):

---

I can reproduce your issue.

I believe my change is a step into the right direction, but unfortunately not enough:

From https://github.com/jtojnar/cmake-snips#assuming-cmake_install_dir-is-relative-path:

> There is no guarantee that variables like `CMAKE_INSTALL_LIBDIR` or `CMAKE_INSTALL_INCLUDEDIR` are relative paths, or even located under `CMAKE_INSTALL_PREFIX`. In fact, the [documentation](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) explicitly mentions that they can be absolute several times.
>
> If you need absolute paths, **never** concatenate `CMAKE_INSTALL_<dir>` to `CMAKE_INSTALL_PREFIX` manually. Use `CMAKE_INSTALL_FULL_<dir>` instead.

My change fixed on occurrence of that, but I suspect that in

https://github.com/google/glog/blob/33696664cba5737098546adcd8e4938730312a69/CMakeLists.txt#L554-L557

and their later uses, the assumption that the `CMAKE_INSTALL_*` (non-`FULL`) paths are relative is still present in some parts.

I'm now trying to make it use the `_FULL_` paths instead, but there's still one case where 2 absolute paths are concatenated.

**Comment by sergiud** [comment] 2021-11-11 13:43
Yes, my assumption about relative paths in `GNUInstallDirs` was incorrect. Thanks for pointing out.

@r-burns Thanks for confirming the changes to work.

**Closed** 2021-11-12 11:06 UTC
Labels: bug
