### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by neostrider** [google/glog#45] opened 2015-07-31 11:03 UTC
I am getting the following error, while running make:

/usr/bin/ld: /usr/local//lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

How to fix it?

**Comment by ukai** [comment] 2015-12-17 07:48
Duplicate of #38 ?

**Closed by ukai** 2015-12-17 07:48 UTC
