### ISSUE TITLE
Flag GLOG_v failed to set in Mac environment and resulting in incorrect printing of logs

### ISSUE THREAD

**Issue by chen2016013** [google/glog#1090] opened 2024-03-28 02:55 UTC
https://github.com/PaddlePaddle/Paddle/issues/61837

<img width="766" alt="7408594f84d0fe4ae09b4b0c138fda6f" src="https://github.com/google/glog/assets/111894720/287351da-f668-4160-a4a7-8258f6cd2582">

![image](https://github.com/google/glog/assets/111894720/ec251dc7-4d06-4613-82dc-3c2ea7f916f2)

![image](https://github.com/google/glog/assets/111894720/710e08af-2753-4fe3-8d3b-3c1c2e70074d)

in the repo of paddlepaddle, We use glog and try to control output log level by the FLAG "GLOG_v". It works well except in the above environment. When running on Mac, GLOG_v doesn't seem to work on this line and it will be print even GLOG_v is set to 0.

**Comment by sergiud** [comment] 2024-03-28 15:45
Thanks for reporting the issue. However, I cannot reproduce the described problem with the latest glog 0.7.0.

A simple test program
```.cpp
#include <glog/logging.h>

int main(int argc, char** argv)
{
    google::InitGoogleLogging(argv[0]);
    VLOG(8) << "foo";
    LOG(INFO) << "test";
}
```
generates the desired output:
```console
$ GLOG_logtostderr=1 GLOG_v=0 ./foo 
I20240328 16:35:36.823674 126464463306304 t.cc:7] test
$ GLOG_logtostderr=1 GLOG_v=8 ./foo 
I20240328 16:36:07.026887 133151090474560 t.cc:6] foo
I20240328 16:36:07.026932 133151090474560 t.cc:7] test
```

In case you still experience the issue with glog 0.7.0 please make sure to provide enough information that would allow to reproduce the problem.

I'm closing the issue in the meantime since there is nothing actionable.

**Closed by sergiud** 2024-03-28 15:45 UTC
Labels: needs reproducer
