### ISSUE TITLE
"make install" failure

### ISSUE THREAD

**Issue by zhouxiangxiang** [google/glog#70] opened 2015-11-18 08:00 UTC
environment:
__uname -a__
Linux localhost.localdomain 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

__make && make install__
_src/demangle.h:80:27: error: expected initializer before 'Demangle'
 bool GOOGLE_GLOG_DLL_DECL Demangle(const char *mangled, char *out, int out_size);_
                           ^
make: *** [src/libglog_la-demangle.lo] Error 1

**Comment by gotope** [comment] 2015-12-07 14:13
encounter the same error, any solution?

**Comment by ukai** [comment] 2015-12-17 07:19
command line to compile it?
do you have wrong config.h somewhere in include path?

**Comment by ukai** [comment] 2015-12-17 07:39
Duplicate of #52

**Closed** 2015-12-17 07:47 UTC
