### ISSUE TITLE
Compile error when installed with vcpkg

### ISSUE THREAD

**Issue by OrientalSiru** [google/glog#1107] opened 2024-06-14 08:30 UTC
I am using the non-CMake version of Visual Studio, and I installed glog with vcpkg. However, I get the following error when trying to include the library:

`Error  C1189   #error:  <glog/logging.h> was not included correctly. See the documention for how to consume the library.`

Tried to resolve the above by adding `#define GLOG_USE_GLOG_EXPORT`, I get another error:

`Error  C4996  google::CustomPrefixCallback': Use PrefixFormatterCallback instead.`

## Repro	
1. Install glog using vcpkg: `.\vcpkg\vcpkg.exe install glog`
2. Create a new visual studio c++ console app
3. Include `#include <glog/logging.h>`
4. Build

**Comment by sergiud** [comment] 2024-06-14 09:56
What is your question? Especially given the compiler messages are self-explanatory.

In general, we do not support non-CMake builds. We also do not maintain the vcpkg version of glog.

If you choose to integrate glog from scratch, you need to replicate the compiler options and defines set by CMake.

**Comment by sergiud** [comment] 2024-06-14 12:59
I'm closing the issue since the problem is clearly caused by incorrect/unsupported glog integration. Note that similar questions have been asked before: #1091 #1079. The documentation also [explicitly states](https://google.github.io/glog/stable/) that Bazel or CMake integration is required. Therefore, the issue is not actionable.

**Closed by sergiud** 2024-06-14 12:59 UTC
Labels: invalid

**Comment by OrientalSiru** [comment] 2024-06-14 17:27
@sergiud Do you know who maintains the vcpkg version? vcpkg claims to support non-CMake builds, so I was hoping it has a solution to make it work with non-CMake.

**Comment by sergiud** [comment] 2024-06-14 17:41
The [documentation](https://google.github.io/glog/stable/packages/) contributed to glog states that the packages are maintained by the [vcpkg project](https://github.com/microsoft/vcpkg).

**Comment by mcassidy04** [comment] 2024-12-14 17:02
Error  C4996  google::CustomPrefixCallback': Use PrefixFormatterCallback instead. 

This is caused by the 
#if defined(__GNUG__)
#  pragma GCC diagnostic pop
#elif defined(_MSC_VER)
#  pragma warning(pop)
#endif  // __GNUG__#  

after line 498 of logging.h being invoked before

[[deprecated("Use InstallPrefixFormatter instead.")]] GLOG_EXPORT void
InitGoogleLogging(const char* argv0, CustomPrefixCallback prefix_callback,
                  void* prefix_callback_data = nullptr);

moving it to follow resolves the deprecation warning error.
