### ISSUE TITLE
build error with ceres library

### ISSUE THREAD

**Issue by YingLiangJiang** [google/glog#948] opened 2023-09-07 01:38 UTC
I use ceres v2.1.0 library with vs2019 by vcpkg and built successfully ,but i got a problem when add head file “#include<ceres/ceres.h>" ,it display "ERROR macro is defined. Define GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the document for detail.".I place the macro definition in front of the header file:#define GOOGLE_GLOG_DLL_DECL #define GLOG_NO_ABBREVIATED_SEVERITIES
  #include "glog/logging.h" ,strangely there are more errors.
I hope to get help ,thank you!

**Comment by sergiud** [comment] 2023-09-07 06:54
`GLOG_NO_ABBREVIATED_SEVERITIES` is defined on Windows automatically if you use CMake or Bazel. Therefore, there must be something else wrong with your setup. Given you did not provide any details, we can only guess what the issue is.

**Comment by sergiud** [comment] 2023-09-07 07:53
Let me close the issue because you use the vcpkg port of glog which we do not maintain. Please refer the vcpkg issue tracker for support.

**Closed by sergiud** 2023-09-07 07:53 UTC
