### ISSUE TITLE
Complie error

### ISSUE THREAD

**Issue by Guozht** [google/glog#284] opened 2018-01-09 02:10 UTC
error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > & (__cdecl*)(class std::basic_ostream<char,struct std::char_traits<char> > &))" (__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@P6AAEAV01@AEAV01@@Z@Z)
 error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::put(char)" (__imp_?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@D@Z)

**Comment by ml232528** [comment] 2018-01-09 09:23
me too
vs2017 x64.
glog = 0.3.5 use Default static library

**Comment by sergiud** [comment] 2018-01-09 09:31
How is this compile error is related glog?

**Comment by ml232528** [comment] 2018-01-09 09:36
use dynamic is ok

**Comment by Guozht** [comment] 2018-01-09 09:37
vs2013 X64
glog = 0.3.4 use Default static library

**Comment by ml232528** [comment] 2018-01-09 09:45
sorry， this error is not caused by glog。

**Comment by sergiud** [comment] 2018-01-09 09:46
I cannot reproduce this problem. Also, the error does not indicate any relation to glog.

Unless you can provide information that exactly allows to reproduce the problem, I'm going to close this PR.

**Comment by ml232528** [comment] 2018-01-09 09:53
Can be reproduced。glog ->lib (not dll) ->/md 。exe->/md。
But this problem has nothing  with GLOG

**Closed** 2018-01-09 10:09 UTC
Labels: invalid, question

**Comment by sergiud** [comment] 2018-01-09 10:54
@ml232528 Still not glog related.
