### ISSUE TITLE
Unable to parse [libunwind] configuration due to downstream [glog] provided and exported 

### ISSUE THREAD

**Issue by FrankXie05** [google/glog#820] opened 2022-04-19 06:32 UTC
Hi, I'm the maintainer of vcpkg.
We received an issue about folly being unable to parse the glog exported the cmake configuration of libunwind.
**Host Environment**

- OS: Debian bookworm/sid
- Compiler: gcc 11.2.0

**To Reproduce**
Reproduce the issue steps: https://pastebin.com/GRSKXpKa
Related `Folly` issue: https://github.com/facebook/folly/issues/1757

**Comment by sergiud** [comment] 2022-04-19 08:40
From the steps you provided it is still not clear 
* what the issue exactly is and 
* what resolution do you expect directly in glog given your example uses vcpkg.

Could you please clarify? Also what glog version is this?

**Comment by FrankXie05** [comment] 2022-04-20 07:00
@sergiud Sorry for the late reply, this is my fault. 
The problem is:  Both `folly` and `glog` export libunwind's cmake configuration(`Findlibunwind.cmake`), but they are not compatible, and if `libwind` is installed by the system, `folly` will use the libunwind provided by the system out of control, which will cause `folly` to be unable to distinguish whether `libunwind` is provided by `glog` or system, that will cause conflicts and errors.
Related comment: https://github.com/facebook/folly/issues/1757#issuecomment-1101800682

**Comment by sergiud** [comment] 2022-04-20 08:05
How is this related to glog and even if it is, what resolution do you expect from glog? As far as I can currently tell, this is not a glog issue.

**Comment by sergiud** [comment] 2022-04-20 22:11
After going through the linked discussions, I'm closing the issue as invalid for the following reasons:
1. Your reproducer uses vcpkg instead of glog's CMake implementation which may cause the problems.
2. `FindUnwind.cmake` [is clearly deployed by glog ](https://github.com/google/glog/blob/b33e3bad4c46c8a6345525fd822af355e5ef9446/CMakeLists.txt#L552-L553) and the CMake error is likely caused by modifications to glog's CMake files introduced by vcpkg
3. `FindLibUnwind.cmake` (which is clearly a different find module) is *not* used by glog, therefore a conflict cannot arise
4. We do not support old versions of glog. Please use the 0.6 release.

You are welcome to rebut the reasons by providing a reproducer that does not require vcpkg and uses the latest glog release.

**Closed by sergiud** 2022-04-20 22:11 UTC
Labels: invalid
