### ISSUE TITLE
Logging From Shared Libraries on Windows

### ISSUE THREAD

**Issue by dcc194** [google/glog#83] opened 2016-01-08 17:08 UTC
I have a cross-platform (Linux & Windows) Qt Application that uses glog for logging (commit: 4d391fe692ae6b9e0105f473945c415a3ce5a401).  The project has a main application with several shared libraries that we wrote.  On Linux (Ubuntu 14.04) glog works as expected.  On Windows (built using mingw-w64 and gcc) any log statement that comes from within a DLL gets written to stdout instead of to the log.  Any log statement from within the main application correctly gets written to the log.  Furthermore, I see `WARNING: Logging before InitGoogleLogging() is written to STDERR` in the standard output for each time a log statement is created from a DLL for the first time (i.e. if I have 5 DLLs, I see that warning 5 times immediately prior to the first log statement from each DLL).

It seems like Glog is not being shared across the DLLs.  I have tried to call InitGoogleLogging from within each DLL to test this theory, but then I get a run time crash with the following error message in stdout:  `Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!`.  So it appears that Glog is not being shared however, I can't initialize it in each DLL.

Full disclosure: I had to tweak port.h in order to get glog to build in mingw-w64 by handling pthreads correctly and not redefining localtime_r, but I don't feel this is related.  

``` diff
 #endif  // _MSC_VER

 // ----------------------------------- THREADS
+#ifndef PTHREAD_ONCE_INIT
 typedef DWORD pthread_t;
 typedef DWORD pthread_key_t;
 typedef LONG pthread_once_t;
 enum { PTHREAD_ONCE_INIT = 0 };   // important that this be 0! for SpinLock
 #define pthread_self  GetCurrentThreadId
 #define pthread_equal(pthread_t_1, pthread_t_2)  ((pthread_t_1)==(pthread_t_2))
+#endif

-inline struct tm* localtime_r(const time_t* timep, struct tm* result) {
-  localtime_s(result, timep);
-  return result;
-}
+//inline struct tm* localtime_r(const time_t* timep, struct tm* result) {
+//  localtime_s(result, timep);
+//  return result;
+//}
```

**Comment by wyl8899** [comment] 2016-02-02 16:35
Also encountered the windows/port.h issue when trying to cross-compile.

Another issue to mention. The headers that are `make install`ed still have the `__declspec(dllimport)` macro definitions, even when the build is configured to produce a static library. They cause "undefined reference to \_imp_[some mangled symbol]" error when linking.

**Comment by davidalbertonogueira** [comment] 2017-09-19 14:26
I have the same problem, but in Linux. How should someone approach these situations, in which a dynamic library uses Glog, and my client application also uses Glog? They cannot both call InitGoogleLogging. But the dynamic library cannot drop that Logging initialization call because it can be used in applications without Glog. Shouldn't exist something like InitGoogleSharedLogging? 
Moreover, how to approach cases when the shared library and the main client use different versions of a library or one of them has Glog coupled with Gflags and the other not? How to make each one point to its "rightful" library?

**Comment by sergiud** [comment] 2018-02-28 17:56
`InitGoogleLogging` should be ideally called only by the application that uses the libraries dependent on glog.

Closing the issue for now, since I cannot reproduce the problem.

**Closed by sergiud** 2018-02-28 17:56 UTC
