### ISSUE TITLE
i build with bazel clang-tidy， loggging.h error: 'chrono' file not found [clang-diagnostic-error]

### ISSUE THREAD

**Issue by boluo250** [google/glog#839] opened 2022-07-13 07:05 UTC
![image](https://user-images.githubusercontent.com/18418363/178671724-b1d6699b-7415-40fc-b438-869acfa5d445.png)

```
**BUILD**
filegroup(
       name = "clang_tidy_config",
       data = [".clang-tidy"],
       visibility = ["//visibility:public"],
)

**WORKSPACE**
load(
    "@bazel_tools//tools/build_defs/repo:git.bzl",
    "git_repository",
)
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
git_repository(
       name = "bazel_clang_tidy",
       commit = "783aa523aafb4a6798a538c61e700b6ed27975a7",
       remote = "https://github.com/erenon/bazel_clang_tidy.git",
)
http_archive(
        name = "com_github_gflags_gflags",
        sha256 = "f6f4f932f5810deb229f16b82a41debaa0a0716670c0cd8ddea046f0bee72a4e",
        strip_prefix = "gflags-v2.1",
        url = "http://gitlab.tsingj.local/external/gflags/-/archive/v2.1/gflags-v2.1.tar.gz",
    )

git_repository(
       name = "com_github_google_glog",
       commit = "c515e1ae2fc8b36ca19362842f9347e9429be7ad",
       remote = "https://github.com/google/glog.git",
)

**.bazelrc** 
build:clang-tidy --aspects @bazel_clang_tidy//clang_tidy:clang_tidy.bzl%clang_tidy_aspect
build:clang-tidy --output_groups=report
build:clang-tidy --@bazel_clang_tidy//:clang_tidy_config=//:clang_tidy_config



**./es_cpp/BUILD**
cc_binary(
    name = "main-es1",
    srcs = ["testaaa.h"],
    deps = [
        "@com_github_google_glog//:glog",
    ],
    copts = [
        "-std=c++17",
    ],
    visibility = ["//visibility:public"],
)

**testaaa.h**
#include "glog/logging.h"
```

**Comment by sergiud** [comment] 2022-07-14 17:48
The very first error (`invalid argument -std=c++17`) indicates that you are compiling the sources probably as C not C++. Therefore, it is clear that including `<chono>` is not meaningful.

**Comment by drigz** [comment] 2022-07-15 23:51
I think you might need to rename `testaaa.h` to `testaaa.cc` to test this properly.

**Comment by sergiud** [comment] 2024-01-23 15:09
I'm closing the issue since the cause is incorrect `clang-tidy` usage.

**Closed by sergiud** 2024-01-23 15:09 UTC
