### ISSUE TITLE
InstallFailureSignalHandler can not get the detailed stack errors

### ISSUE THREAD

**Issue by kintzhao** [google/glog#777] opened 2022-01-04 09:22 UTC
**this is my test code: test.cpp**, glog is  v0.5.0

```cpp
#include <glog/logging.h>
 
void bar(int x) {
  CHECK_EQ(x, 1);
}
 
void foo(int x) {
  bar(x + 1);
}

int main(int argc, char** argv) {
  google::InstallFailureSignalHandler();
  foo(1);
}
```

build :
```console
g++ -g -O3 test.cpp -lglog -o test
```

**My result Output, But it has not the detailed stack error!**

```console
kint@kint:/tmp/test$ ./test 
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0104 17:09:37.170971 11615 test.cpp:4] Check failed: x == 1 (2 vs. 1) 
*** Check failure stack trace: ***
*** Aborted at 1641287377 (unix time) try "date -d @1641287377" if you are using GNU date ***
PC: @     0x7fa7af57dfb7 gsignal
*** SIGABRT (@0x3e800002d5f) received by PID 11615 (TID 0x7fa7b02c8740) from PID 11615; stack trace: ***
    @     0x7fa7af57e040 (unknown)
    @     0x7fa7af57dfb7 gsignal
    @     0x7fa7af57f921 abort
    @     0x7fa7afedb1f9 (unknown)
    @     0x7fa7afedd0cd google::LogMessage::Fail()
    @     0x7fa7afedef33 google::LogMessage::SendToLog()
    @     0x7fa7afedcc28 google::LogMessage::Flush()
    @     0x7fa7afedf999 google::LogMessageFatal::~LogMessageFatal()
    @     0x560754badd4c (unknown)
    @     0x560754badba3 (unknown)
    @     0x7fa7af560bf7 __libc_start_main
    @     0x560754badbda (unknown)
Aborted (core dumped)
```

Test by the reference [Google glog prints no stack trace](https://stackoverflow.com/questions/38062352/google-glog-prints-no-stack-trace)

**Comment by kintzhao** [comment] 2022-01-04 09:23
ubuntu 18.04  
 g++ -v 
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by sergiud** [comment] 2022-01-04 16:52
@fdgkhdkgh Thanks for looking into the issue.

@kintzhao You seem to be confusing a detailed stack trace with symbol resolution. There's clearly a detailed stack trace present. What is missing are symbol names. Given your problem is not reproducible, you need to find out why symbols are not resolved in your particular case.

**Comment by kintzhao** [comment] 2022-01-05 02:17
`kint@kint:~$ uname -a
Linux kint 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
kint@kint:~$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
kint@kint:~$ 
`

**Comment by kintzhao** [comment] 2022-01-05 02:29
kint@kint:/tmp/test$ file test
test: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=03eb02089288b6c25d198177f36c22def7b213d8, with debug_info, not stripped

**Comment by kintzhao** [comment] 2022-01-05 02:40
kint@kint:/tmp/test$ g++ -ggdb   test.cpp -lglog -o test 
kint@kint:/tmp/test$ ldd test
	linux-vdso.so.1 (0x00007fff68f36000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f6ed7c48000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6ed78bf000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6ed76a7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6ed72b6000)
	libgflags.so.2.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2.2 (0x00007f6ed7091000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f6ed6e76000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6ed6c57000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6ed68b9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6ed807c000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f6ed6693000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6ed648f000)

**Comment by sergiud** [comment] 2022-02-28 12:46
Let me close the issue since your problem cannot be reproduced and we're already preparing the 0.6 release.

You can test glog 0.6.0-rc1 and report back in case you still observe the issue and provide a full reproducer, i.e. a `CMakeLists.txt` and a minimum working example as you initially did.

**Closed by sergiud** 2022-02-28 12:46 UTC
Labels: incomplete
