### ISSUE TITLE
v0.6.0: symbolize unit test fails again in Release mode

### ISSUE THREAD

**Issue by jstiefel** [google/glog#870] opened 2022-11-07 10:40 UTC
When building and testing glog v0.6.0 in `Release` mode, the unit test of `symbolize` fails. If I build and test in `Debug` mode, it succeeds. This was previously mentioned in this issue https://github.com/google/glog/issues/435 and was fixed in v0.5.0. I also tried it in v0.5.0 and there, it succeeds in both `Release` and `Debug` mode.

Built with Ubuntu 20.04.5, g++-9.

**Comment by sergiud** [comment] 2022-11-07 11:24
Our CI runs tests both in debug and release mode and does not exhibit the described problem. The failure is likely specific to your setup and therefore we need a full reproducer.

**Comment by jstiefel** [comment] 2022-11-07 17:23
I'm running it in a basic VSCode Devcontainer:

devcontainer.json:

```
{
	"name": "Ubuntu",
	"image": "ubuntu:20.04",

	"settings": {
		"terminal.integrated.defaultProfile.linux": "bash"
	},
        "postCreateCommand": "apt-get update && apt-get -y install git build-essential cmake",
        "customizations": {
               "vscode": {
                     "extensions": ["ms-vscode.cmake-tools", "ms-vscode.cpptools-themes", "ms-vscode.cpptools-extension-pack", "twxs.cmake", "ms-vscode.cpptools", "cschlosser.doxdocgen"]
        }
    }
}

```
and CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.16)

project(test_proj VERSION 0.0.1 LANGUAGES CXX)

option(WITH_GFLAGS OFF)
option(BUILD_SHARED_LIBS OFF) # for GLOG
set(CMAKE_BUILD_TYPE Release)

include(FetchContent)

FetchContent_Declare(
  googletest
  GIT_REPOSITORY https://github.com/google/googletest.git
  GIT_TAG        release-1.11.0
)

FetchContent_Declare(
  glog
  GIT_REPOSITORY https://github.com/google/glog
  GIT_TAG        v0.6.0   
)

FetchContent_MakeAvailable(glog)
FetchContent_MakeAvailable(googletest)

enable_testing()
include(GoogleTest)
```

**Comment by sergiud** [comment] 2022-11-07 17:37
Thanks. This issue is duplicate of #630.

**Closed by sergiud** 2022-11-07 17:37 UTC
Labels: duplicate

**Comment by jstiefel** [comment] 2022-11-07 17:59
Oh, ok. However, here I think `WITH_GTEST` is `ON` per default and the problem has to do with the `Release` mode compared to the linked issue. But may be the same issue in the end.

**Comment by sergiud** [comment] 2022-11-07 18:03
`WITH_GTEST` is not the problem (see the discussion). TL;DR: either set `BUILD_SHARED_LIBS=ON` or `WITH_TLS=OFF`.
